require("scrollbar").setup({
    show = true,
    show_in_active_only = true,
    set_highlights = true,
    folds = 1000, 
    max_lines = false,
    hide_if_all_visible = true,
    throttle_ms = 100,
    handle = {
        text = " ",
        blend = 30,
        highlight = "CursorColumn",
        hide_if_all_visible = true,
    },
    marks = {
        Cursor = {
            text = "•",
            priority = 0,
            highlight = "Normal",
        },
        Search = {
            text = { "-", "=" },
            priority = 1,
            color = "#FF8800",
            highlight = "Search",
        },
        Error = {
            text = { "-", "=" },
            priority = 2,
            highlight = "DiagnosticVirtualTextError",
        },
        Warn = {
            text = { "-", "=" },
            priority = 3,
            highlight = "DiagnosticVirtualTextWarn",
        },
        Info = {
            text = { "-", "=" },
            priority = 4,
            highlight = "DiagnosticVirtualTextInfo",
        },
        Hint = {
            text = { "-", "=" },
            priority = 5,
            highlight = "DiagnosticVirtualTextHint",
        },
        Misc = {
            text = { "-", "=" },
            priority = 6,
            highlight = "Normal",
        },
        GitAdd = {
            text = "█",
            priority = 7,
            color = "#98be65",
            highlight = "GitSignsAdd",
        },
        GitChange = {
            text = "█",
            priority = 7,
            color = "#98be65",
            highlight = "GitSignsChange",
        },
        GitDelete = {
            text = "█",
            priority = 7,
            color = "#ec5f67",
            highlight = "GitSignsDelete",
        },
    },
    excluded_buftypes = {
        "terminal",
    },
    excluded_filetypes = {
        "cmp_docs",
        "cmp_menu",
        "noice",
        "prompt",
        "TelescopePrompt",
    },
    autocmd = {
        render = {
            "BufWinEnter",
            "TabEnter",
            "TermEnter",
            "WinEnter",
            "CmdwinLeave",
            "TextChanged",
            "VimResized",
            "WinScrolled",
        },
        clear = {
            "BufWinLeave",
            "TabLeave",
            "TermLeave",
            "WinLeave",
        },
    },
    handlers = {
        cursor = true,
        diagnostic = true,
        gitsigns = true,
        handle = true,
        search = true,
        ale = false,
    },
})
